import com.fasterxml.jackson.databind.ObjectMapper;
import enums.CarBrand;
import models.Car;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'harshita.k' at '6/1/16 4:07 PM' with Gradle 2.4
 *
 * @author harshita.k, @date 6/1/16 4:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("Yay project setup done! Hello Gradle!!");
        Car c = new Car(CarBrand.AUDI);
        System.out.println("The car brand is " + c.getCarBrand());

        ObjectMapper objectMapper = new ObjectMapper();

        String carJson =
                "{ \"carBrand\" : \"TATA\"}";
        try {
            Car car = objectMapper.readValue(carJson, Car.class);
            System.out.println("The car brand is " + car.getCarBrand());
        } catch (Exception e) {
            System.out.println("Unable to deserialize");
        }

    }
}
