import enums.CarBrand;
import models.Car;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'harshita.k' at '6/1/16 4:07 PM' with Gradle 2.4
 *
 * @author harshita.k, @date 6/1/16 4:07 PM
 */
public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Car c = new Car(CarBrand.AUDI);
        assertTrue("The brand of the car should be 'AUDI'", (c.getCarBrand() == CarBrand.AUDI));
    }
}
